backend:
  name: git-gateway
  branch: add-cms-feature # Branch to update (optional; defaults to master)
  local_backend: true

media_folder: "assets/images"

collections:
  - name: "Home"
    label: "Home Page Content"
    files:
      - label: "Hero"
        name: "hero"
        file: "content/Home/hero.json"
        format: "json"
        fields:
          - { label: img, name: image, widget: image }
          - { label: title, name: title, widget: string }
